name: Using reusable workflows
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'  # Only install if cache was not hit
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'  # Only install if cache was not hit
        run: npm ci
      - name: Test code
        id: run-tests   # Assign an ID to reference the step outcome
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'  # if at step level, Conditional upload on test failure, && used as logical AND falure() is a function used to check if the previous step failed
        uses: actions/upload-artifact@v6
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'  # Only install if cache was not hit
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    uses: ./.github/workflows/reusable.yml  # Call the reusable workflow defined in .github/workflows/reusable.yml
    with:
      artifact-name: 'dist-files'  # Pass the artifact name as an input to the reusable workflow, which will be used in the deploy job defined in that workflow
    secrets:
      DEPLOYMENT_TOKEN:  abc # ${{ secrets.DEPLOYMENT_TOKEN }}  we need to add literal value here
  report:
    needs: [lint, test, build, deploy]
    if: failure()     # Only run if any of the previous jobs failed, at job level
    runs-on: ubuntu-latest
    steps:
      - name: Generate report
        run: |
          echo "Lint Status: ${{ needs.lint.result }}"
          echo "Test Status: ${{ needs.test.result }}"
          echo "Build Status: ${{ needs.build.result }}"
          echo "Deploy Status: ${{ needs.deploy.result }}"
